version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:    
    commands:
      - yum install git -y
      - ECR_REPOSITORY_URI=${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
      - echo Logging in to Amazon ECR...
      - $(docker login -u AWS -p $(aws ecr get-login-password --region ${AWS_REGION}) ${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com)
  build: 
    commands:
      - /bin/bash ./build.sh
